### ISSUE TITLE
Protótipo de Baixa Fidelidade

### ISSUE THREAD

**Issue by Gustavo-Nogueira** [Interacao-Humano-Computador/2020.1-Estagiarios.com#10]
## Tasks:

- [x] Confecção do do protótipo;
- [x] Planejamento da avaliação do protótipo;
- [x] Avaliação e relato dos resultados da avaliação do protótipo.

**Comment by Gustavo-Nogueira** [comment]
finalizada
